const getCountryRegion = (country) => {
  const data = {
    "Afghanistan": "Asia",
    "Africa": "",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Anguilla": "North America",
    "Antigua and Barbuda": "North America",
    "Argentina": "South America",
    "Armenia": "Asia",
    "Aruba": "North America",
    "Asia": "",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Bahamas": "North America",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Barbados": "North America",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Belize": "North America",
    "Benin": "Africa",
    "Bermuda": "North America",
    "Bhutan": "Asia",
    "Bolivia": "South America",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "South America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Cape Verde": "Africa",
    "Cayman Islands": "North America",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "South America",
    "China": "Asia",
    "Colombia": "South America",
    "Comoros": "Africa",
    "Congo": "Africa",
    "Costa Rica": "North America",
    "Cote d'Ivoire": "Africa",
    "Croatia": "Europe",
    "Cuba": "North America",
    "Curacao": "North America",
    "Cyprus": "Europe",
    "Czechia": "Europe",
    "Democratic Republic of Congo": "Africa",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "North America",
    "Dominican Republic": "North America",
    "Ecuador": "South America",
    "Egypt": "Africa",
    "El Salvador": "North America",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Eswatini": "Africa",
    "Ethiopia": "Africa",
    "Europe": "",
    "European Union": "",
    "Faeroe Islands": "Europe",
    "Falkland Islands": "South America",
    "Fiji": "Oceania",
    "Finland": "Europe",
    "France": "Europe",
    "French Polynesia": "Oceania",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Asia",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Gibraltar": "Europe",
    "Greece": "Europe",
    "Greenland": "North America",
    "Grenada": "North America",
    "Guatemala": "North America",
    "Guernsey": "Europe",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "South America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Hong Kong": "Asia",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "International": "",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Isle of Man": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Jamaica": "North America",
    "Japan": "Asia",
    "Jersey": "Europe",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Kosovo": "Europe",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Asia",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Macao": "Asia",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Oceania",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "North America",
    "Micronesia (country)": "Oceania",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Montserrat": "North America",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar": "Asia",
    "Namibia": "Africa",
    "Nauru": "Oceania",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Caledonia": "Oceania",
    "New Zealand": "Oceania",
    "Nicaragua": "North America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North America": "",
    "North Macedonia": "Europe",
    "Northern Cyprus": "Asia",
    "Norway": "Europe",
    "Oceania": "",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Palestine": "Asia",
    "Panama": "North America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Qatar": "Asia",
    "Romania": "Europe",
    "Russia": "Europe",
    "Rwanda": "Africa",
    "Saint Helena": "Africa",
    "Saint Kitts and Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent and the Grenadines": "North America",
    "Samoa": "Oceania",
    "San Marino": "Europe",
    "Sao Tome and Principe": "Africa",
    "Saudi Arabia": "Asia",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South America": "",
    "South Korea": "Asia",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "South America",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syria": "Asia",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Timor": "Asia",
    "Togo": "Africa",
    "Tonga": "Oceania",
    "Trinidad and Tobago": "North America",
    "Tunisia": "Africa",
    "Turkey": "Asia",
    "Turks and Caicos Islands": "North America",
    "Tuvalu": "Oceania",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "South America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Vatican": "Europe",
    "Venezuela": "South America",
    "Vietnam": "Asia",
    "Wallis and Futuna": "Oceania",
    "World": "",
    "Yemen": "Asia",
    "Zambia": "Africa",
    "Zimbabwe": "Africa"
  }
  return data[country]
}

const parseTime = d3.timeParse("%Y-%m-%d")

const continentColors = {
  Asia: '#a83232',
  Europe: '#a89332',
  Africa: '#64a832',
  'North America': '#32a88f',
  'South America': '#3a32a8',
  'Oceania': '#f542c8'
}

const regionList = new Set(["Asia", "Europe", "Africa", "North America", "South America", "Oceania"])

const parseData = (list, metaData) => {
  let earliestDate = new Date('9999-12-31')
  let latestDate = new Date('0000-01-01')
  let maxAveDailyNewCases = 0

  const numberOfCountries = metaData?.countriesPerRegion[list[0].location] ?? 1
  const newList = list.map(element => {
    const elementDate = new Date(element.date)
    if (elementDate < earliestDate) {
      earliestDate = elementDate
    }
    if (elementDate > latestDate) {
      latestDate = elementDate
    }
    if (maxAveDailyNewCases < parseInt(element.dailyNewCases / numberOfCountries)) {
      maxAveDailyNewCases = parseInt(element.dailyNewCases / numberOfCountries)
    }

    return {
      location: element.location,
      date: d3.timeParse("%Y-%m-%d")(element.date),
      aveDailyNewCases: (parseFloat(element.dailyNewCases) / numberOfCountries),
      dailyNewCases: parseInt(element.dailyNewCases),
      dailyDeaths: parseInt(element.dailyDeaths)
    }
  })

  return {
    newList,
    earliestDate,
    latestDate,
    maxAveDailyNewCases
  }
}

const responseToData = {
  'Contact Tracing': '../finalData/responseData/contact_tracing.json',
  'Face Covering': '../finalData/responseData/facial_coverings.json',
  'Income Support': '../finalData/responseData/income_support.json',
  'Int. Travel Restrictions': '../finalData/responseData/international_travel_controls.json',
  'Public Gathering Restrictions': '../finalData/responseData/restriction_gatherings.json',
  'Internal Travel Restrictions': '../finalData/responseData/restrictions_internal_movements.json',
  'School Closures': '../finalData/responseData/school_closures.json',
  'Overall Stringency': '../finalData/responseData/stringency_index.json',
  'Workplace Closures': '../finalData/responseData/workplace_closures.json'
}